### Shapash Model Overview
https://shapash.readthedocs.io/en/latest/

##### With this tutorial you:
Understand how to create a Shapash SmartPredictor to make prediction and have local explanation in production with a simple use case.

This tutorial describes the different steps from training the model to Shapash SmartPredictor deployment. A more detailed tutorial allows you to know more about the SmartPredictor Object.

Contents:

- Build a Regressor
- Compile Shapash SmartExplainer
- From Shapash SmartExplainer to SmartPredictor
- Save Shapash Smartpredictor Object in pickle file
- Make a prediction

In [47]:
import seaborn as sns

In [48]:
df=sns.load_dataset('tips')

In [49]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [50]:
### Divide the dataset into independent and dependent dataset
y=df['tip']
X=df[df.columns.difference(['tip'])]

In [51]:
X.head()

   day     sex  size smoker    time  total_bill
0  Sun  Female     2     No  Dinner       16.99
1  Sun    Male     3     No  Dinner       10.34
2  Sun    Male     3     No  Dinner       21.01
3  Sun    Male     2     No  Dinner       23.68
4  Sun  Female     4     No  Dinner       24.59

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [53]:
X['day']=X['day'].cat.codes
X['sex']=X['sex'].cat.codes
X['smoker']=X['smoker'].cat.codes
X['time']=X['time'].cat.codes

C:\Users\drbhi\AppData\Local\Temp\ipykernel_13492\4105089070.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\drbhi\AppData\Local\Temp\ipykernel_13492\4105089070.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\drbhi\AppData\Local\Temp\ipykernel_13492\4105089070.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\drbhi\AppData\Local\Temp\ipykernel_13492\4105089070.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [54]:
X

     day  sex  size  smoker  time  total_bill
0      3    1     2       1     1       16.99
1      3    0     3       1     1       10.34
2      3    0     3       1     1       21.01
3      3    0     2       1     1       23.68
4      3    1     4       1     1       24.59
..   ...  ...   ...     ...   ...         ...
239    2    0     3       1     1       29.03
240    2    1     2       0     1       27.18
241    2    0     2       0     1       22.67
242    2    0     2       1     1       17.82
243    0    1     2       1     1       18.78

[244 rows x 6 columns]

In [55]:
### Train Test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.75,random_state=1)

In [56]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=200).fit(X_train,y_train)

#### Lets Understand Our Model With Shapash 
In this section, we use the SmartExplainer Object from shapash.

- It allows users to understand how the model works with the specified data.
- This object must be used only for data mining step. Shapash provides another object for deployment.

In [109]:
!pip install shapash[report]

Requirement already satisfied: shapash[report] in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (2.4.2)
Requirement already satisfied: plotly>=5.0.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (5.14.1)
Requirement already satisfied: matplotlib>=3.2.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (3.7.5)
Requirement already satisfied: numpy>1.18.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (1.24.3)
Requirement already satisfied: pandas>1.0.2 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (2.0.3)
Requirement already satisfied: shap>=0.38.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (0.44.1)
Requirement already satisfied: Flask<2.3.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (2.2.5)
Requirement already satisfied: dash>=2.3.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (2.15.0)
Requirement already satisfied: dash-bootstrap-components>=1.1.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (1.5.0)
Requirement already satisfied: dash-core-components>=2.0.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (2.0.0)
Requirement already satisfied: dash-daq>=0.5.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (0.5.0)
Requirement already satisfied: dash-html-components>=2.0.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (2.0.0)
Requirement already satisfied: dash-renderer==1.8.3 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (1.8.3)
Requirement already satisfied: dash-table>=5.0.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (5.0.0)
Requirement already satisfied: nbformat>4.2.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (5.8.0)
Requirement already satisfied: numba>=0.53.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (0.58.1)
Requirement already satisfied: scikit-learn<1.4,>=1.0.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (1.3.2)
Requirement already satisfied: category-encoders>=2.6.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (2.6.3)
Requirement already satisfied: scipy>=0.19.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (1.10.1)
Requirement already satisfied: nbconvert>=6.0.7 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (7.4.0)
Requirement already satisfied: papermill>=2.0.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (2.5.0)
Requirement already satisfied: jupyter-client>=7.4.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (8.2.0)
Requirement already satisfied: seaborn==0.12.2 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (0.12.2)
Requirement already satisfied: notebook in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (6.5.4)
Requirement already satisfied: Jinja2>=2.11.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (3.1.2)
Requirement already satisfied: phik in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shapash[report]) (0.12.4)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from category-encoders>=2.6.0->shapash[report]) (0.14.1)
Requirement already satisfied: patsy>=0.5.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from category-encoders>=2.6.0->shapash[report]) (0.5.6)
Requirement already satisfied: importlib-resources in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from category-encoders>=2.6.0->shapash[report]) (5.12.0)
Requirement already satisfied: Werkzeug<3.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from dash>=2.3.1->shapash[report]) (2.3.6)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from dash>=2.3.1->shapash[report]) (4.5.0)
Requirement already satisfied: requests in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from dash>=2.3.1->shapash[report]) (2.31.0)
Requirement already satisfied: retrying in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from dash>=2.3.1->shapash[report]) (1.3.4)
Requirement already satisfied: nest-asyncio in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from dash>=2.3.1->shapash[report]) (1.5.6)
Requirement already satisfied: setuptools in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from dash>=2.3.1->shapash[report]) (56.0.0)
Requirement already satisfied: importlib-metadata in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from dash>=2.3.1->shapash[report]) (6.6.0)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from Flask<2.3.0->shapash[report]) (2.1.2)
Requirement already satisfied: click>=8.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from Flask<2.3.0->shapash[report]) (8.1.7)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from Jinja2>=2.11.0->shapash[report]) (2.1.2)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from jupyter-client>=7.4.0->shapash[report]) (5.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from jupyter-client>=7.4.0->shapash[report]) (2.8.2)
Requirement already satisfied: pyzmq>=23.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from jupyter-client>=7.4.0->shapash[report]) (25.0.2)
Requirement already satisfied: tornado>=6.2 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from jupyter-client>=7.4.0->shapash[report]) (6.3.1)
Requirement already satisfied: traitlets>=5.3 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from jupyter-client>=7.4.0->shapash[report]) (5.9.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from matplotlib>=3.2.0->shapash[report]) (1.0.7)
Requirement already satisfied: cycler>=0.10 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from matplotlib>=3.2.0->shapash[report]) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from matplotlib>=3.2.0->shapash[report]) (4.39.4)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from matplotlib>=3.2.0->shapash[report]) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from matplotlib>=3.2.0->shapash[report]) (23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from matplotlib>=3.2.0->shapash[report]) (9.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from matplotlib>=3.2.0->shapash[report]) (3.0.9)
Requirement already satisfied: beautifulsoup4 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from nbconvert>=6.0.7->shapash[report]) (4.12.3)
Requirement already satisfied: bleach in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from nbconvert>=6.0.7->shapash[report]) (6.0.0)
Requirement already satisfied: defusedxml in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from nbconvert>=6.0.7->shapash[report]) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from nbconvert>=6.0.7->shapash[report]) (0.2.2)
Requirement already satisfied: mistune<3,>=2.0.3 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from nbconvert>=6.0.7->shapash[report]) (2.0.5)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from nbconvert>=6.0.7->shapash[report]) (0.7.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from nbconvert>=6.0.7->shapash[report]) (1.5.0)
Requirement already satisfied: pygments>=2.4.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from nbconvert>=6.0.7->shapash[report]) (2.15.1)
Requirement already satisfied: tinycss2 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from nbconvert>=6.0.7->shapash[report]) (1.2.1)
Requirement already satisfied: fastjsonschema in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from nbformat>4.2.0->shapash[report]) (2.16.3)
Requirement already satisfied: jsonschema>=2.6 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from nbformat>4.2.0->shapash[report]) (4.17.3)
Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from numba>=0.53.1->shapash[report]) (0.41.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from pandas>1.0.2->shapash[report]) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from pandas>1.0.2->shapash[report]) (2023.3)
Requirement already satisfied: pyyaml in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from papermill>=2.0.0->shapash[report]) (6.0)
Requirement already satisfied: tqdm>=4.32.2 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from papermill>=2.0.0->shapash[report]) (4.66.2)
Requirement already satisfied: entrypoints in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from papermill>=2.0.0->shapash[report]) (0.4)
Requirement already satisfied: tenacity>=5.0.2 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from papermill>=2.0.0->shapash[report]) (8.2.2)
Requirement already satisfied: joblib>=1.1.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn<1.4,>=1.0.1->shapash[report]) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn<1.4,>=1.0.1->shapash[report]) (3.1.0)
Requirement already satisfied: slicer==0.0.7 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shap>=0.38.1->shapash[report]) (0.0.7)
Requirement already satisfied: cloudpickle in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from shap>=0.38.1->shapash[report]) (3.0.0)
Requirement already satisfied: argon2-cffi in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from notebook->shapash[report]) (21.3.0)
Requirement already satisfied: ipython-genutils in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from notebook->shapash[report]) (0.2.0)
Requirement already satisfied: ipykernel in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from notebook->shapash[report]) (6.23.1)
Requirement already satisfied: Send2Trash>=1.8.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from notebook->shapash[report]) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from notebook->shapash[report]) (0.17.1)
Requirement already satisfied: prometheus-client in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from notebook->shapash[report]) (0.16.0)
Requirement already satisfied: nbclassic>=0.4.7 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from notebook->shapash[report]) (0.5.6)
Requirement already satisfied: colorama in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from click>=8.0->Flask<2.3.0->shapash[report]) (0.4.6)
Requirement already satisfied: zipp>=0.5 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from importlib-metadata->dash>=2.3.1->shapash[report]) (3.15.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from jsonschema>=2.6->nbformat>4.2.0->shapash[report]) (23.1.0)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from jsonschema>=2.6->nbformat>4.2.0->shapash[report]) (1.3.10)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from jsonschema>=2.6->nbformat>4.2.0->shapash[report]) (0.19.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-client>=7.4.0->shapash[report]) (3.5.0)
Requirement already satisfied: pywin32>=300 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-client>=7.4.0->shapash[report]) (306)
Requirement already satisfied: jupyter-server>=1.8 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from nbclassic>=0.4.7->notebook->shapash[report]) (2.5.0)
Requirement already satisfied: notebook-shim>=0.2.3 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from nbclassic>=0.4.7->notebook->shapash[report]) (0.2.3)
Requirement already satisfied: six in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from patsy>=0.5.1->category-encoders>=2.6.0->shapash[report]) (1.16.0)
Requirement already satisfied: pywinpty>=1.1.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from terminado>=0.8.3->notebook->shapash[report]) (2.0.10)
Requirement already satisfied: argon2-cffi-bindings in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from argon2-cffi->notebook->shapash[report]) (21.2.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from beautifulsoup4->nbconvert>=6.0.7->shapash[report]) (2.4.1)
Requirement already satisfied: webencodings in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from bleach->nbconvert>=6.0.7->shapash[report]) (0.5.1)
Requirement already satisfied: comm>=0.1.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->notebook->shapash[report]) (0.1.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->notebook->shapash[report]) (1.6.7)
Requirement already satisfied: ipython>=7.23.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->notebook->shapash[report]) (8.12.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->notebook->shapash[report]) (0.1.6)
Requirement already satisfied: psutil in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->notebook->shapash[report]) (5.9.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from requests->dash>=2.3.1->shapash[report]) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from requests->dash>=2.3.1->shapash[report]) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from requests->dash>=2.3.1->shapash[report]) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from requests->dash>=2.3.1->shapash[report]) (2023.7.22)
Requirement already satisfied: backcall in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from ipython>=7.23.1->ipykernel->notebook->shapash[report]) (0.2.0)
Requirement already satisfied: decorator in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from ipython>=7.23.1->ipykernel->notebook->shapash[report]) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from ipython>=7.23.1->ipykernel->notebook->shapash[report]) (0.18.2)
Requirement already satisfied: pickleshare in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from ipython>=7.23.1->ipykernel->notebook->shapash[report]) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from ipython>=7.23.1->ipykernel->notebook->shapash[report]) (3.0.38)
Requirement already satisfied: stack-data in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from ipython>=7.23.1->ipykernel->notebook->shapash[report]) (0.6.2)
Requirement already satisfied: anyio>=3.1.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook->shapash[report]) (3.6.2)
Requirement already satisfied: jupyter-events>=0.4.0 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook->shapash[report]) (0.6.3)
Requirement already satisfied: jupyter-server-terminals in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook->shapash[report]) (0.4.4)
Requirement already satisfied: websocket-client in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook->shapash[report]) (1.5.1)
Requirement already satisfied: cffi>=1.0.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->notebook->shapash[report]) (1.15.1)
Requirement already satisfied: sniffio>=1.1 in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from anyio>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook->shapash[report]) (1.3.0)
Requirement already satisfied: pycparser in c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook->shapash[report]) (2.21)

In [110]:
from shapash import SmartExplainer

In [111]:
SE = SmartExplainer(model=regressor)

In [116]:
SE.compile(
x=X_test, 

 
)

INFO: Shap explainer type - <shap.explainers._tree.TreeExplainer object at 0x000001C8E8EA55B0>

In [117]:
SE

#### Lets Understand the results of your trained model
Then, we can easily get a first summary of the explanation of the model results.

- Here, we chose to get the 3 most contributive features for each prediction.
- We used a wording to get features names more understandable in operationnal case.

In [118]:
app = SE.run_app(title_story='Tips Dataset')

c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\shapash\webapp\utils\utils.py:40: FutureWarning:

Index.is_numeric is deprecated. Use pandas.api.types.is_any_real_numeric_dtype instead

INFO:root:Your Shapash application run on http://LAPTOP-0VK27G7V:8050/
INFO:root:Use the method .kill() to down your app.
Exception in thread Thread-17:
Traceback (most recent call last):
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [WinError 10049] The requested address is not valid in its context

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\http\client.py", line 1007, in _send_output
    self.send(msg)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\http\client.py", line 947, in send
    self.connect()
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001C8BC69A4F0>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=8050): Max retries exceeded with url: /_alive_817a5cf2-7e0c-4e55-8399-c2a28e42f6c6 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8BC69A4F0>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\shapash\utils\threading.py", line 31, in __run
    self.__run_backup()
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\shapash\explainer\smart_explainer.py", line 1059, in <lambda>
    target=lambda: self.smartapp.app.run_server(debug=False, host=host, port=port)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\dash\dash.py", line 2175, in run_server
    self.run(*args, **kwargs)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\dash\dash.py", line 2066, in run
    jupyter_dash.run_app(
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\dash\_jupyter.py", line 399, in run_app
    raise final_error
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\dash\_jupyter.py", line 386, in run_app
    wait_for_app()
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\retrying.py", line 266, in call
    raise attempt.get()
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\dash\_jupyter.py", line 383, in wait_for_app
    raise err
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\dash\_jupyter.py", line 370, in wait_for_app
    req = requests.get(alive_url)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\drbhi\appdata\local\programs\python\python38\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=8050): Max retries exceeded with url: /_alive_817a5cf2-7e0c-4e55-8399-c2a28e42f6c6 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8BC69A4F0>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))

In [87]:
predictor = SE.to_smartpredictor()

AttributeError: 'SmartExplainer' object has no attribute 'backend'

In [18]:
predictor.save('./predictor.pkl')

NameError: name 'predictor' is not defined

In [19]:
from shapash.utils.load_smartpredictor import load_smartpredictor
predictor_load = load_smartpredictor('./predictor.pkl')

FileNotFoundError: [Errno 2] No such file or directory: './predictor.pkl'

#### Make a prediction with your SmartPredictor
In order to make new predictions and summarize local explainability of your model on new datasets, you can use the method add_input of the SmartPredictor.

- The add_input method is the first step to add a dataset for prediction and explainability.
- It checks the structure of the dataset, the prediction and the contribution if specified.
- It applies the preprocessing specified in the initialisation and reorder the features with the order used by the model. (see the documentation of this method)
- In API mode, this method can handle dictionnaries data which can be received from a GET or a POST request.
- Add data
- The x input in add_input method doesn't have to be encoded, add_input applies preprocessing.

In [20]:
predictor_load.add_input(x=X, ypred=y)

NameError: name 'predictor_load' is not defined

In [21]:
detailed_contributions = predictor_load.detail_contributions()

NameError: name 'predictor_load' is not defined

In [22]:
detailed_contributions.head()

NameError: name 'detailed_contributions' is not defined

#### Summarize explanability of the predictions
- You can use the summarize method to summarize your local explainability
- This summary can be configured with modify_mask method so that you have explainability that meets your operational needs.

In [23]:

predictor_load.modify_mask(max_contrib=3)

NameError: name 'predictor_load' is not defined

In [24]:
explanation = predictor_load.summarize()

NameError: name 'predictor_load' is not defined

In [25]:
explanation.head()

NameError: name 'explanation' is not defined